#!/bin/bash

#valgrind --leak-check=full \
#         --show-leak-kinds=all \
#         --track-origins=yes \
#         --verbose \
#         --log-file=valgrind-out.txt \
#gdb --args \
./bin/qLD-compute -inputList input_list.txt \
                  -output test_dataset/output/covid \
                  -ploidy haploid \
                  -r2limit 0.0 \
                  -mdf \
                  -threads 4 \
                  -competing
