#!/bin/bash
#gdb --args \
./bin/qLD-parse-2MDF -input test_dataset/input/test_10_10_errors.gz \
                     -output test_dataset/input/test_10_10_errors_2.gz \
                     -ploidy haploid \
                     -seed 0 \
                     -impute

#valgrind --tool=massif \
#./bin/qLD-compute -inputList ilist_10.txt \
#                  -r2limit 0.0 \
#                  -threads 4 \
#                  -mdf \
#                  -blis \
#                  -ploidy haploid \
#                  -output test_dataset/report_test_gemm.txt

#
#./bin/qLD-compute -input test_dataset/input/test_10_10 \
#                  -input2 test_dataset/input/test_10_10 \
#                  -posWmin1 1 \
#                  -posWmax1 1000 \
#                  -posWmin2 1 \
#                  -posWmax2 2000 \
#                  -r2limit 0.0 \
#                  -threads 1 \
#                  -mdf \
#                  -blis \
#                  -ploidy haploid \
#                  -output test_dataset/report_test_gemm.txt
